### ISSUE TITLE
Better relay-pulse control request.

### ISSUE THREAD

**Issue by bsp9493** [davidnewhall/indigo-8channel-relay#6]
Hi... great work on the indigo release.

totally new to programming and haven't quite figured out the whole indigo plug in format, but I have a request/question.

as you noted, this works great for sprinkler control (on/off) control of the relays.

I see you have also included a way to "pulse" a specific relay.  From what i can see the only way to do this is by creating a control page, and using a server action to "send relay pulse signal".  This works great, however, my question is as follows...

I have gotten away from using control pages if possible and instead use my devices/actions directly from the tabs on the indigo mobile app. (in this case, I would like to use the devices tab to find my garage door opener)  however, when the device is created, it only appears to allow directly for on/off control.

Is there a way to add the pulse option to the basic device control?

one other suggestion/request... it's probably just me, but do you have an indigodomo user forum?  If so can you point me at it.  I'm thinking we could generate a lot more discussion about this simple but useful little 8ch relay board.

Thanx in advance, you help is appreciated.

d

**Comment by bsp9493** [comment]
Thanx... i will give that a shot!

Interesting little device, with a bunch of potential!

d

**Comment by davidnewhall** [comment]
Please reach back out if I can be of further assistance.

**Comment by bsp9493** [comment]
ohhhh all excited about the sprinkler option…  I was going to request exactly that!


ran into a problem though when I installed the new plugin 1.0…

I am unable to create sprinkler device…

I get the following errors…

Error (client)                  _sendClosedConfigUi3() caught exception: LowLevelBadParameterError
   8 Channel Network Relay Error   Error in plugin execution UiClosed3:

Traceback (most recent call last):
  File "plugin.py", line 121, in closedDeviceFactoryUi
  File "plugin.py", line 346, in set_device_states
TypeError: cannot concatenate 'str' and 'int' objects

   Error (client)                  doPluginDeviceFactory requires at least one root device

Jan 3, 2019, 4:36:09 PM
 
   8 Channel Network Relay         Sent "new device" on
   8 Channel Network Relay         Sent "new device" off
   Error (client)                  _sendClosedConfigUi3() caught exception: LowLevelBadParameterError
   8 Channel Network Relay Error   Error in plugin execution UiClosed3:

Traceback (most recent call last):
  File "plugin.py", line 82, in closedDeviceFactoryUi
IndexError: index 0 out of list range

**Comment by bsp9493** [comment]
ohhhh all excited about the sprinkler option…  I was going to request exactly that!


ran into a problem though when I installed the new plugin 1.0…

I am unable to create sprinkler device…

get the following errors…

Error (client)                  _sendClosedConfigUi3() caught exception: LowLevelBadParameterError
   8 Channel Network Relay Error   Error in plugin execution UiClosed3:

Traceback (most recent call last):
  File "plugin.py", line 121, in closedDeviceFactoryUi
  File "plugin.py", line 346, in set_device_states
TypeError: cannot concatenate 'str' and 'int' objects

   Error (client)                  doPluginDeviceFactory requires at least one root device

Jan 3, 2019, 4:36:09 PM
 
   8 Channel Network Relay         Sent "new device" on
   8 Channel Network Relay         Sent "new device" off
   Error (client)                  _sendClosedConfigUi3() caught exception: LowLevelBadParameterError
   8 Channel Network Relay Error   Error in plugin execution UiClosed3:

Traceback (most recent call last):
  File "plugin.py", line 82, in closedDeviceFactoryUi
IndexError: index 0 out of list range
